M48
; DRILL file {KiCad 9.0.0} date 2025-07-20T20:25:43-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-20T20:25:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X2.6341Y-1.5673
X2.6341Y-1.7949
T2
X2.5079Y-0.9213
X2.5079Y-2.8976
X4.4843Y-2.8976
M30
